# Generated by Django 3.0.7 on 2020-06-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='parent',
            new_name='parent_todo',
        ),
    ]
