# Generated by Django 3.0.7 on 2020-06-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200612_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='parent_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Label'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='parent_todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Todo'),
        ),
    ]
