# Generated by Django 3.0.7 on 2020-06-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200612_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
