# Generated by Django 3.0.7 on 2020-06-21 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_label_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='_root_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_label', to='todo.Label'),
        ),
    ]
