# Generated by Django 3.0.7 on 2020-06-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
